%
%  genetics.m
%  Copyright (C) 2012 Eric Bakan
%
%  This program is free software: you can redistribute it and/or modify
%  it under the terms of the GNU General Public License as published by
%  the Free Software Foundation, either version 3 of the License, or
%  (at your option) any later version.
%
%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.
%
%  You should have received a copy of the GNU General Public License
%  along with this program.  If not, see <http://www.gnu.org/licenses/>.
%

%% Reads in and graphs data from logfiles generated by Processor
dat = csvread('winner.log');
time = dat(:,1);
theta = dat(:,2);
omega = dat(:,3);
alpha = dat(:,4);
power = dat(:,5);
steadytime = dat(:,6);
goal = dat(:,7);
score = dat(:,8);
figure;
subplot(611);
plot(time, theta);
hold on;
plot(time, goal);
hold off;
title('revolutions vs time');
subplot(612);
plot(time, omega);
title('angular velocity vs time');
subplot(613);
plot(time,alpha);
title('angular acceleration vs time');
subplot(614);
plot(time,power);
title('power vs time');
subplot(615);
plot(time,score);
title('score vs time');
subplot(616);
plot(time,steadytime(:)>0);
title('at goal (bool) vs time');
